### PR TITLE
fix: some ui issues

### PR DESCRIPTION
**Pull request by nurbolatk**
This PR fixes some of the profile search UI issues:

1. Big padding on mobile. This is how it looked on my Samsung flip 5:

2. The "too many profiles" text could cause an overflow on some desktops due to big fixed width. Instead I reset it to fill the available space 
Screenshot 2024-03-25 at 5 34 00 PM
4. The search cities input was too small on small devices due to `w-fit` on its container. Instead, I added this rule: on small screens take the full device width, and on bigger screens don't grow more than 320px
Screenshot 2024-03-25 at 5 34 58 PM

These fixes should make the UI more robust. I initially tried to solve the carousel issue, but it was very tricky. I still couldn't replicate the issue, however, I got some ideas:
1. State updates happening somewhere that is causing jumps
2. The Carousel component implementation is not ideal

I see that we have a lot of states, it would be great to reduce their number.
I will implement this Carousel component by myself, still using the `embla` library.
Then retest this bug to see if it helped

### CODE REVIEW

**Comment by NayeemurR** [comment]
Hey Nurbolat, this is one of the issues I see with the current implementation!

Screenshot 2024-03-29 at 11 10 27 AM
Screenshot 2024-03-29 at 11 22 37 AM

The first screenshot is with the code in this PR. Do you see how the "This may be a lot of profiles to go through. If you'd like, you can provide your city to narrow down the results. Or you can simply just go through all of them." text goes all the way across the line?

This makes it look strange. The text should be like the second image shown.

Other than that, mobile fix is really great and tablet fix looks awesome! It's just desktop view has that one error.

Also, I think this component has been changed in another PR, so this may cause merge conflicts. How can we overcome this?

**Comment by nurbolatk** [comment]
Thanks! I will reduce the max allowed width of the text on desktops.

Regarding merge conflicts, we don't have any right now. The "Merge pull request" button is green and active. But it can become inactive after I apply the changes; I don't know yet.

Merge conflicts appear when 2 different PRs touch the same code. Usually, teams work in a way that allows each member to work on a different part of the code base. Otherwise, merge conflicts are hard to avoid, and you just have to deal with them

**Comment by nurbolatk** [comment]
this is what it will look like -

image

The text will take 70% of the parent's width, but if the screen happens to be too wide, it won't go more than 52rems (832 px on most devices)

**Review by NayeemurR — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
